server:
  port: 8083

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

gcp:
  bucket-name: ${GCP_BUCKET_NAME:my-memories-media-bucket}
  project-id: ${GCP_PROJECT_ID:my-memories-project}
  credentials-location: ${GCP_CREDENTIALS_LOCATION:}
  local-storage-dir: ${LOCAL_STORAGE_DIR:./uploaded-media}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
